## Problem Statement

### Business Context

The healthcare industry is rapidly evolving, with professionals facing increasing challenges in managing vast volumes of medical data while delivering accurate and timely diagnoses. The need for quick access to comprehensive, reliable, and up-to-date medical knowledge is critical for improving patient outcomes and ensuring informed decision-making in a fast-paced environment.

Healthcare professionals often encounter information overload, struggling to sift through extensive research and data to create accurate diagnoses and treatment plans. This challenge is amplified by the need for efficiency, particularly in emergencies, where time-sensitive decisions are vital. Furthermore, access to trusted, current medical information from renowned manuals and research papers is essential for maintaining high standards of care.

To address these challenges, healthcare centers can focus on integrating systems that streamline access to medical knowledge, provide tools to support quick decision-making, and enhance efficiency. Leveraging centralized knowledge platforms and ensuring healthcare providers have continuous access to reliable resources can significantly improve patient care and operational effectiveness.

**Common Questions to Answer**

1. **Critical Care Protocols:** "What is the protocol for managing sepsis in a critical care unit?"

2. **General Surgery:** "What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?"

3. **Dermatology:** "What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?"

4. **Neurology:** "What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?"

### Objective

As an AI specialist, your task is to develop a RAG-based AI solution using renowned medical manuals to address healthcare challenges. The objective is to **understand** issues like information overload, **apply** AI techniques to streamline decision-making, **analyze** its impact on diagnostics and patient outcomes, **evaluate** its potential to standardize care practices, and **create** a functional prototype demonstrating its feasibility and effectiveness.

### Data Description

The **Merck Manuals** are medical references published by the American pharmaceutical company Merck & Co., that cover a wide range of medical topics, including disorders, tests, diagnoses, and drugs. The manuals have been published since 1899, when Merck & Co. was still a subsidiary of the German company Merck.

The manual is provided as a PDF with over 4,000 pages divided into 23 sections.

## Installing and Importing Necessary Libraries and Dependencies

In [ ]:
# Install required libraries
!pip install -q langchain_community==0.3.27 \
              langchain==0.3.27 \
              chromadb==1.0.15 \
              pymupdf==1.26.3 \
              tiktoken==0.9.0\
              datasets==4.0.0 \
              evaluate==0.4.5 \
              langchain_openai==0.3.30

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 51.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 69.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.5/19.5 MB 98.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.1/24.1 MB 89.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 78.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 27.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.6/4.6 MB 128.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 461.3/461.3 kB 44.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 96.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 948.6/948.6 kB 60.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.2/137.2 kB 15.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.6/204.6 kB 23.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.5/66.5 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 5.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langgraph 1.2.9 requires langchain-core<2,>=1.4.7, but you have langchain-core 0.3.86 which is incompatible.
google-adk 2.4.0 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.44.0 which is incompatible.
google-adk 2.4.0 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.44.0 which is incompatible.
langgraph-prebuilt 1.1.0 requires langchain-core>=1.3.1, but you have langchain-core 0.3.86 which is incompatible.
langgraph-sdk 0.4.2 requires langchain-core<2,>=1.4.0, but you have langchain-core 0.3.86 which is incompatible.

In [ ]:
# Install llama-cpp-python with GPU support for running LLaMA models
!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.2.45 --force-reinstall --upgrade --no-cache-dir -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.7/36.7 MB 271.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 187.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 271.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 246.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 203.6 MB/s eta 0:00:00
  Building wheel for llama-cpp-python (pyproject.toml) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.5.1 which is incompatible.
langgraph 1.2.9 requires langchain-core<2,>=1.4.7, but you have langchain-core 0.3.86 which is incompatible.
google-adk 2.4.0 requires opentelemetry-api<=1.42.1,>=1.39, but you have opentelemetry-api 1.44.0 which is incompatible.
google-adk 2.4.0 requires opentelemetry-sdk<=1.42.1,>=1.39, but you have opentelemetry-sdk 1.44.0 which is incompatible.
langgraph-prebuilt 1.1.0 requires langchain-core>=1.3.1, but you have langchain-core 0.3.86 which is incompatible.
langgraph-sdk 0.4.2 requires langchain-core<2,>=1.4.0, but you have langchain-core 0.3.86 which is incompatible.

In [ ]:
!pip install -U langchain-huggingface

Collecting langchain-huggingface
  Downloading langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)
Collecting huggingface-hub<2.0.0,>=0.33.4 (from langchain-huggingface)
  Downloading huggingface_hub-1.26.0-py3-none-any.whl.metadata (16 kB)
Collecting langchain-core<2.0.0,>=1.2.31 (from langchain-huggingface)
  Downloading langchain_core-1.5.3-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: tokenizers<1.0.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from langchain-huggingface) (0.22.2)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (6.0.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.67.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.10.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.13.4)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.17.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.33.4->langchain-huggingface) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.1.1)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.9.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.32.4)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (15.0.1)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.8.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.31->langchain-huggingface) (2.5.0)
Downloading langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)
Downloading huggingface_hub-1.26.0-py3-none-any.whl (780 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 780.4/780.4 kB 19.9 MB/s eta 0:00:00
Downloading langchain_core-1.5.3-py3-none-any.whl (561 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 561.7/561.7 kB 46.0 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, langchain-core, langchain-huggingface
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.20.3
    Uninstalling huggingface-hub-0.20.3:
      Successfully uninstalled huggingface-hub-0.20.3
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 0.3.86
    Uninstalling langchain-core-0.3.86:
      Successfully uninstalled langchain-core-0.3.86
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-openai 0.3.30 requires langchain-core<1.0.0,>=0.3.74, but you have langchain-core 1.5.3 which is incompatible.
langchain-community 0.3.27 requires langchain-core<1.0.0,>=0.3.66, but you have langchain-core 1.5.3 which is incompatible.
langchain 0.3.27 requires langchain-core<1.0.0,>=0.3.72, but you have langchain-core 1.5.3 which is incompatible.
Successfully installed huggingface-hub-1.26.0 langchain-core-1.5.3 langchain-huggingface-1.2.2

In [ ]:
# Install Hugging Face Hub client library for downloading models
!pip install huggingface_hub==0.20.3 -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 330.1/330.1 kB 7.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
diffusers 0.39.0 requires huggingface-hub<2.0,>=0.34.0, but you have huggingface-hub 0.20.3 which is incompatible.
peft 0.19.1 requires huggingface_hub>=0.25.0, but you have huggingface-hub 0.20.3 which is incompatible.
datasets 4.0.0 requires huggingface-hub>=0.24.0, but you have huggingface-hub 0.20.3 which is incompatible.
sentence-transformers 5.6.0 requires huggingface-hub>=0.23.0, but you have huggingface-hub 0.20.3 which is incompatible.
transformers 5.13.1 requires huggingface-hub<2.0,>=1.5.0, but you have huggingface-hub 0.20.3 which is incompatible.
accelerate 1.14.0 requires huggingface_hub>=0.21.0, but you have huggingface-hub 0.20.3 which is incompatible.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.20.3 which is incompatible.

**Note**:
- After running the above cell, kindly restart the runtime (for Google Colab) or notebook kernel (for Jupyter Notebook), and run all cells sequentially from the next cell.
- On executing the above line of code, you might see a warning regarding package dependencies. This error message can be ignored as the above code ensures that all necessary libraries and their dependencies are maintained to successfully execute the code in ***this notebook***.

## **LLM with Prompt Engineering Response**

#### **Download LLaMA-2 13B Chat Model**

In [ ]:
from huggingface_hub import hf_hub_download

model_name_or_path = "TheBloke/Llama-2-13B-chat-GGUF"
model_basename = "llama-2-13b-chat.Q5_K_M.gguf"

model_path = hf_hub_download(
    repo_id=model_name_or_path,
    filename=model_basename
)

print(model_path)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

/root/.cache/huggingface/hub/models--TheBloke--Llama-2-13B-chat-GGUF/snapshots/4458acc949de0a9914c3eab623904d4fe999050a/llama-2-13b-chat.Q5_K_M.gguf

**Inference :** This code logs into Hugging Face using your access token and downloads the LLaMA-2 13B GGUF model.
The downloaded model path is stored in model_path for loading in the next step.

#### **Initialize LLaMA Model with Configuration**

In [ ]:
from llama_cpp import Llama

lcpp_llm = Llama(
    model_path=model_path,   # Path to the downloaded GGUF model
    n_threads=4,             # Number of CPU threads to use
    n_batch=512,             # Batch size for prompt processing
    n_gpu_layers=-1,         # Offload all possible layers to the GPU
    n_ctx=4096               # Context window
)

llama_model_loader: loaded meta data with 19 key-value pairs and 363 tensors from /root/.cache/huggingface/hub/models--TheBloke--Llama-2-13B-chat-GGUF/snapshots/4458acc949de0a9914c3eab623904d4fe999050a/llama-2-13b-chat.Q5_K_M.gguf (version GGUF V2)
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = LLaMA v2
llama_model_loader: - kv   2:                       llama.context_length u32              = 4096
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 5120
llama_model_loader: - kv   4:                          llama.block_count u32              = 40
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 13824
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 40
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 40
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 17
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  13:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  14:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  15:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  16:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  17:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  18:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   81 tensors
llama_model_loader: - type q5_K:  241 tensors
llama_model_loader: - type q6_K:   41 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V2
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 4096
llm_load_print_meta: n_embd           = 5120
llm_load_print_meta: n_head           = 40
llm_load_print_meta: n_head_kv        = 40
llm_load_print_meta: n_layer          = 40
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 5120
llm_load_print_meta: n_embd_v_gqa     = 5120
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 13824
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 13B
llm_load_print_meta: model ftype      = Q5_K - Medium
llm_load_print_meta: model params     = 13.02 B
llm_load_print_meta: model size       = 8.60 GiB (5.67 BPW)
llm_load_print_meta: general.name     = LLaMA v2
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.28 MiB
llm_load_tensors: offloading 40 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 41/41 layers to GPU
llm_load_tensors:        CPU buffer size =   107.42 MiB
llm_load_tensors:      CUDA0 buffer size =  8694.21 MiB
...................................................................................................
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      CUDA0 KV buffer size =  3200.00 MiB
llama_new_context_with_model: KV self size  = 3200.00 MiB, K (f16): 1600.00 MiB, V (f16): 1600.00 MiB
llama_new_context_with_model:  CUDA_Host input buffer size   =    19.04 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =   368.02 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    10.00 MiB
llama_new_context_with_model: graph splits (measure): 3
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 |
Model metadata: {'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'general.architecture': 'llama', 'llama.context_length': '4096', 'general.name': 'LLaMA v2', 'llama.embedding_length': '5120', 'llama.feed_forward_length': '13824', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'llama.rope.dimension_count': '128', 'llama.attention.head_count': '40', 'tokenizer.ggml.bos_token_id': '1', 'llama.block_count': '40', 'llama.attention.head_count_kv': '40', 'general.quantization_version': '2', 'tokenizer.ggml.model': 'llama', 'general.file_type': '17'}

**Inference :** This initializes the downloaded LLaMA model with CPU and GPU settings.
The model is now ready to generate responses for user prompts

In [ ]:
# Provides an example and answer anchor to guide the model in giving concise, evidence-based responses without echoing the question.
system_prompt = """
You are a medical expert AI assistant. Respond with concise, evidence-based answers.
"""

user_prompt = """
Example:
Q: What are the common symptoms of appendicitis?
A: Common symptoms include abdominal pain (usually starting near the navel), nausea, vomiting, and fever.
References: Mayo Clinic, UpToDate

Now answer:
Q: What is the protocol for managing sepsis in a critical care unit?
A:
"""

#### **Response Function**

In [ ]:
# function to generate, process, and return the response from the LLM
def prompt_engineering_response(user_prompt):
    # Put the system message first, then the user question, then anchor with "Answer:"
    prompt = f"""{system_prompt}

Question: {user_prompt}

Answer:"""

    # Generate a response from the LLaMA model
    response = lcpp_llm(
    prompt,
    max_tokens=512,
    temperature=0.3,
    top_p=0.95,
    stop=["Question:", "Q:"],
    echo=False
)

    # Extract and return the response text
    response_text = response["choices"][0]["text"].strip()
    return response_text

**Inference :** This function sends the prompt to the LLaMA model and generates a response.
The parameters control the response length and randomness for more accurate medical answers.

## Question Answering using LLM with Prompt Engineering

### Question 1: What is the protocol for managing sepsis in a critical care unit?

In [ ]:
question_1 = "What is the protocol for managing sepsis in a critical care unit?"

answer_1 = prompt_engineering_response(question_1)

print("Question:", question_1)
print("Answer:", answer_1)

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =     277.50 ms /   455 runs   (    0.61 ms per token,  1639.63 tokens per second)
llama_print_timings: prompt eval time =     436.94 ms /    48 tokens (    9.10 ms per token,   109.85 tokens per second)
llama_print_timings:        eval time =   28209.07 ms /   454 runs   (   62.13 ms per token,    16.09 tokens per second)
llama_print_timings:       total time =   30673.34 ms /   502 tokens

Question: What is the protocol for managing sepsis in a critical care unit?
Answer: The Surviving Sepsis Campaign (SSC) guidelines provide a comprehensive protocol for managing sepsis in a critical care unit. Here are the key elements of the protocol:

1. Early recognition and diagnosis: Use clinical criteria and biomarkers to identify patients with suspected sepsis. Confirm the diagnosis with blood cultures and other tests as needed.
2. Rapid administration of antibiotics: Start broad-spectrum antibiotics within the first hour of recognition of sepsis, and within 3 hours of recognition in severe sepsis or septic shock.
3. Fluid resuscitation: Administer crystalloid fluids initially, and consider vasopressors if fluid responsiveness is not achieved.
4. Oxygenation: Provide oxygen therapy as needed, and consider non-invasive or invasive ventilation if hypoxia persists despite optimal oxygen therapy.
5. Monitoring: Closely monitor vital signs, laboratory values, and organ function.
6. Source control: Identify and manage the source of infection, if present.
7. Adjunctive therapies: Consider adjunctive therapies such as corticosteroids, vasopressors, and blood products as needed.
8. Septic shock management: Use vasopressors and mechanical ventilation to manage septic shock. Consider extracorporeal membrane oxygenation (ECMO) in refractory cases.
9. Close monitoring and escalation: Closely monitor patients and escalate care as needed, including transfer to an intensive care unit or ECMO if necessary.
10. Early recognition of organ dysfunction: Monitor for signs of organ dysfunction and address any issues promptly to prevent further progression of sepsis.

It is important to note that these recommendations may vary based on individual patient factors and local institutional protocols. Consult with a qualified healthcare professional for specific guidance on managing sepsis in a critical care unit.

### Question 2: What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?

In [ ]:
question_2 = "What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?"

answer_2 = prompt_engineering_response(question_2)

print("Question:", question_2)
print("Answer:", answer_2)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =     260.94 ms /   305 runs   (    0.86 ms per token,  1168.83 tokens per second)
llama_print_timings: prompt eval time =     418.98 ms /    37 tokens (   11.32 ms per token,    88.31 tokens per second)
llama_print_timings:        eval time =   21486.21 ms /   304 runs   (   70.68 ms per token,    14.15 tokens per second)
llama_print_timings:       total time =   24150.08 ms /   341 tokens

Question: What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?
Answer: Appendicitis is inflammation of the appendix, typically caused by obstruction of the lumen of the appendix. The common symptoms of appendicitis include:

* Severe pain in the abdomen, often starting near the navel and then moving to the lower right abdomen
* Nausea and vomiting
* Loss of appetite
* Fever
* Abdominal tenderness and guarding (muscle tension)
* Abdominal swelling

Medications can help manage symptoms such as pain and fever, but they do not cure appendicitis. Surgery is necessary to remove the inflamed appendix. The surgical procedure most commonly used to treat appendicitis is an appendectomy, which involves removing the inflamed appendix through an incision in the abdomen. In some cases, the appendectomy may be laparoscopic, which involves making several small incisions in the abdomen and using a camera and specialized instruments to remove the appendix.

It is important to note that delaying treatment can lead to complications such as the appendix rupturing, which can cause peritonitis, a potentially life-threatening infection of the abdominal cavity. Therefore, if you suspect you or someone else may have appendicitis, it is important to seek medical attention immediately.

### Question 3: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?

In [ ]:
question_3 = "What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?"

answer_3 = prompt_engineering_response(question_3)

print("Question:", question_3)
print("Answer:", answer_3)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     535.28 ms
llama_print_timings:      sample time =      72.12 ms /   117 runs   (    0.62 ms per token,  1622.34 tokens per second)
llama_print_timings: prompt eval time =     382.70 ms /    41 tokens (    9.33 ms per token,   107.13 tokens per second)
llama_print_timings:        eval time =    8184.12 ms /   116 runs   (   70.55 ms per token,    14.17 tokens per second)
llama_print_timings:       total time =    9069.09 ms /   157 tokens

Question: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?
Answer: Sudden patchy hair loss, also known as alopecia areata, can be caused by an autoimmune response, genetics, stress, or hormonal imbalances. Effective treatments include topical corticosteroids, minoxidil, anthralin, and immunotherapy. In severe cases, oral medications such as prednisone or cyclosporine may be prescribed. It is essential to consult a dermatologist to determine the underlying cause and develop an appropriate treatment plan.

### Question 4:  What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?

In [ ]:
question_4 = "What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?"

answer_4 = prompt_engineering_response(question_4)

print("Question:", question_4)
print("Answer:", answer_4)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     535.28 ms
llama_print_timings:      sample time =     222.74 ms /   380 runs   (    0.59 ms per token,  1706.06 tokens per second)
llama_print_timings: prompt eval time =     392.12 ms /    35 tokens (   11.20 ms per token,    89.26 tokens per second)
llama_print_timings:        eval time =   28747.19 ms /   379 runs   (   75.85 ms per token,    13.18 tokens per second)
llama_print_timings:       total time =   30839.88 ms /   414 tokens

Question: What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?
Answer: Treatment options for a person who has sustained a physical injury to brain tissue and experienced temporary or permanent impairment of brain function depend on the severity and location of the injury, as well as the individual's overall health and medical history. Here are some common treatment options that may be recommended:

1. Medications: Pain relievers, anti-seizure drugs, and other medications may be prescribed to manage symptoms such as pain, seizures, and inflammation.
2. Rehabilitation therapy: Physical, occupational, and speech therapy may be necessary to help the individual regain lost functions and improve cognitive and motor skills.
3. Surgery: In some cases, surgery may be necessary to relieve pressure on the brain, repair damaged blood vessels, or remove a tumor that may be causing the injury.
4. Stem cell therapy: Stem cell therapy is a promising area of research that may help repair damaged brain tissue and improve functional outcomes.
5. Neuroplasticity-based therapy: This type of therapy aims to improve the brain's ability to adapt and compensate for lost functions by using non-invasive techniques such as electrical stimulation and cognitive training.
6. Lifestyle modifications: Making lifestyle modifications such as regular exercise, stress management, and a healthy diet can help improve overall health and well-being, which may aid in the recovery process.

It's important to note that the most effective treatment plan will depend on the individual's specific needs and circumstances, and should be developed by a team of medical professionals with expertise in neurology and rehabilitation.

#### **Create and Display Results DataFrame**

In [ ]:
# Create the DataFrame
import pandas as pd
prompt_result_df = pd.DataFrame({
    "questions": [ question_1, question_2],
    "prompt_Engineering_responses": [answer_1, answer_2]})

prompt_result_df.head()

,questions,prompt_Engineering_responses
0,What is the protocol for managing sepsis in a ...,The Surviving Sepsis Campaign (SSC) guidelines...
1,"What are the common symptoms for appendicitis,...","Appendicitis is inflammation of the appendix, ..."

In [ ]:
# Create the DataFrame
import pandas as pd
prompt_result_df = pd.DataFrame({
    "questions": [question_1, question_2, question_3, question_4],
    "prompt_Engineering_responses": [answer_1, answer_2, answer_3, answer_4]
})

prompt_result_df.head()

,questions,prompt_Engineering_responses
0,What is the protocol for managing sepsis in a ...,The Surviving Sepsis Campaign (SSC) guidelines...
1,"What are the common symptoms for appendicitis,...","Appendicitis is inflammation of the appendix, ..."
2,What are the effective treatments or solutions...,"Sudden patchy hair loss, also known as alopeci..."
3,What treatments are recommended for a person w...,Treatment options for a person who has sustain...

#### **Observations:**

* The prompt engineering approach successfully generated responses for all four medical questions, demonstrating that the LLaMA-2 model can understand and answer domain-specific queries based on its pre-trained knowledge.

* Although the responses were relevant and informative, they were not grounded in the Merck Manual dataset. Since no external knowledge source was used, the model may produce generalized answers and may not always provide the most accurate or up-to-date medical information.

## **RAG Response**

## **Data Preparation for RAG**

### **Loading the data**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from langchain.document_loaders import PyMuPDFLoader

# Path to the PDF in Google Drive
pdf_path = "/content/drive/MyDrive/GenAI_Placement/medical_diagnosis_manual.pdf"


# Create the loader
loader = PyMuPDFLoader(pdf_path)

# Load the PDF as LangChain Documents
document = loader.load()

print(f"Total pages loaded: {len(document)}")

Total pages loaded: 4114

### Data Overview

Display the content of page number 16 and 17

In [ ]:
#Do not run this only for understanding
for i in range(15, 17):
    print(f"Page {i+1}")
    print(document[i].page_content)
    print("-" * 80)

Page 16
degree. The book received critical acclaim and sold over 2 million copies. The Second Home Edition was
released in 2003. Merck's commitment to providing comprehensive, understandable medical information
to all people continued with The Merck Manual Home Health Handbook, published in 2009.
The Merck Manual of Health & Aging , published in 2004, continued Merck's commitment to education
and geriatric care, providing information on aging and the care of older people in words understandable
by the lay public.
In 2008, The Merck Manual of Patient Symptoms  was introduced to complement The Merck Manual
and was intended to help newcomers to clinical diagnosis approach patients who present with certain
common symptoms.
As part of its commitment to ensuring that all who need and want medical information can get it, Merck
provides the content of these Merck Manuals on the web for free (www.merckmanuals.com). Registration
is not required, and use is unlimited. The web publications are continuously updated to ensure that the
information is as up-to-date as possible.
Merck also supports the community of chemists and others with the need to know about chemical
compounds with The Merck Index. First published in 1889, this publication actually predates The Merck
Manual and is the most widely used text of its kind. The Merck Veterinary Manual  was first published in
1955. It provides information on the health care of animals and is the preeminent text in its field.
Merck & Co., Inc., is one of the world's largest pharmaceutical companies. Merck is committed to
providing excellent medical information and, as part of that effort, continues to proudly provide all of The
Merck Manuals as a service to the community.
Contents
Guide for Readers…viii
Abbreviations…ix
Editors and Editorial Board…xi
Consultants…xiii
Contributors…xv
1 Nutritional Disorders… 1
2 Gastrointestinal Disorders… 67
3 Hepatic and Biliary Disorders… 203
4 Musculoskeletal and Connective Tissue Disorders… 281
5 Ear, Nose, Throat, and Dental Disorders… 411
6 Eye Disorders… 535
7 Dermatologic Disorders… 629
8 Endocrine and Metabolic Disorders… 755
9 Hematology and Oncology… 915
10 Immunology; Allergic Disorders… 1077
11 Infectious Diseases… 1143
12 Psychiatric Disorders… 1483
The Merck Manual of Diagnosis & Therapy, 19th Edition
Front Matter
6
rvssenthil@gmail.com
7RPZD4O59E
This file is meant for personal use by rvssenthil@gmail.com only.
Sharing or publishing the contents in part or full is liable for legal action.
--------------------------------------------------------------------------------
Page 17
13 Neurologic Disorders… 1583
14 Pulmonary Disorders… 1823
15 Cardiovascular Disorders… 2015
16 Critical Care Medicine… 2243
17 Genitourinary Disorders… 2303
18 Gynecology and Obstetrics… 2479
19 Pediatrics… 2691
20 Geriatrics… 3069
21 Clinical Pharmacology… 3165
22 Injuries; Poisoning… 3187
23 Special Subjects… 3371
Appendixes… 3489
Ready Reference Guides…3489
Normal Laboratory Values…3491
Trade Names of Some Commonly Used Drugs…3505
Index…3521
Guide For Readers
The Contents (p. vii) shows the pages on which readers can find the Editors and Editorial Board
members, consultants, additional reviewers, and contributors, as well as titles of sections, appendixes,
and the index. Thumb tabs with appropriate abbreviations and section numbers mark each section and
the index.
Each Section begins with its own table of contents, listing chapters and topics in that section. Chapters
are numbered serially from the beginning to the end of the book.
The Index is highly detailed and contains many cross-entries. In addition, readers will find many cross-
references throughout the text to specific pages where additional or related information can be found.
Running heads carry the section number and title on left-hand pages and the chapter number and title
on right-hand pages.
Abbreviations and symbols, used throughout the text as essential space savers, are listed on pages ix
and x. Other abbreviations in the text are expanded at first mention in the chapter or topic.
Tables and figures are referenced in the index but are not listed in a separate table of contents. An
insert of color plates contains photographs of many eye, ear, endocrine, skin, and gynecologic disorders
as well as infectious diseases.
Laboratory values in the book are given in conventional units. In most cases, SI units follow in
parentheses. Appendix II contains several tables listing normal laboratory values for many tests
conducted on blood, plasma, serum, urine, CSF, and stool.
The Merck Manual of Diagnosis & Therapy, 19th Edition
Front Matter
7
rvssenthil@gmail.com
7RPZD4O59E
This file is meant for personal use by rvssenthil@gmail.com only.
Sharing or publishing the contents in part or full is liable for legal action.
--------------------------------------------------------------------------------

**Inference :** This code displays the contents of pages 16 and 17 from the medical manual.
It helps verify that the PDF has been loaded correctly and contains readable text

## **Data Chunking**

Split the document into Chunks and display the total chunks

In [ ]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

# Create the text splitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

# Split the document into chunks
docs = text_splitter.split_documents(document)

# Display the total number of chunks
print(f"Total chunks: {len(docs)}")

Total chunks: 17984

**Inference :** This code splits the loaded PDF into smaller overlapping text chunks for efficient retrieval.
Chunking helps the RAG system retrieve only the most relevant information instead of searching the entire document

### Embedding

Generate Vector Embeddings for Text Chunks Using OpenAI

In [ ]:
import os

os.environ["HUGGINGFACEHUB_API_TOKEN"] = "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"

In [ ]:
from langchain_huggingface import HuggingFaceEndpointEmbeddings

embedding_model = HuggingFaceEndpointEmbeddings(
    model="sentence-transformers/all-MiniLM-L6-v2",
    huggingfacehub_api_token="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"
)

In [ ]:
from langchain.vectorstores import Chroma

vectorstore = Chroma.from_documents(
    documents=docs,
    embedding=embedding_model,
    persist_directory="chroma_db"
)

print("Vector store created successfully!")

Vector store created successfully!

### Retriever

Retrieval and Response Generation using Vector Search

In [ ]:
retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 3}
)

In [ ]:
medical_system_message = """
You are an AI assistant designed to support healthcare professionals by providing evidence-based, concise, and accurate responses using authoritative medical sources, such as the Merck Manuals.

Your goal is to help clinicians, researchers, and healthcare teams quickly access reliable medical knowledge to improve patient outcomes, support decision-making, and reduce information overload.

User input will include context extracted from trusted medical sources. This context will begin with the token:

###Context
The context may include excerpts from the Merck Manuals, clinical guidelines, or peer-reviewed medical literature, including titles, sections, authors, and other relevant metadata.

When crafting your response:
- Use only the provided context to answer the question.
- Provide concise, clinically relevant, and accurate answers.
- Include the source (title, section, and page/section reference) when applicable.
- If the context does not contain relevant information, respond: "Sorry, this is out of my knowledge base."
- Do NOT provide personal medical advice or treatment recommendations outside of the context.
- Maintain a professional, neutral, and safe tone appropriate for healthcare communication.

Example response format:

Answer:
[Answer based on context]

Source:
[Source title, section, page]
"""

In [ ]:
medical_user_message_template = """
###Context
Here are relevant excerpts from the Merck Manuals or other authoritative medical sources:
{context}

###Question
{question}
"""

### Response Function

In [ ]:
def generate_rag_response(
    user_input,
    retriever,
    llm,
    system_message,
    user_message_template,
    k=5,
    max_tokens=500,
    temperature=0.3,
    top_p=0.95,
):

    # Retrieve relevant documents
    retrieved_docs = retriever.invoke(user_input)

    # Build context
    context = "\n\n".join([doc.page_content for doc in retrieved_docs[:k]])

    # Create prompt
    prompt = f"""
{system_message}

{user_message_template.format(
    context=context,
    question=user_input
)}

Answer:
"""

    # Generate answer using llama-cpp
    output = llm(
        prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        stop=["###Question"],
        echo=False,
    )

    return output["choices"][0]["text"].strip()

## Question Answering using RAG

### Question 1: What is the protocol for managing sepsis in a critical care unit?

In [ ]:
question_1 = "What is the protocol for managing sepsis in a critical care unit?"

response_with_rag_1 = generate_rag_response(
    user_input=question_1,
    retriever=retriever,
    llm=lcpp_llm,
    system_message=medical_system_message,
    user_message_template=medical_user_message_template,
)

print(response_with_rag_1)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =      84.58 ms /   142 runs   (    0.60 ms per token,  1678.80 tokens per second)
llama_print_timings: prompt eval time =    2896.03 ms /  1116 tokens (    2.60 ms per token,   385.36 tokens per second)
llama_print_timings:        eval time =   11971.81 ms /   141 runs   (   84.91 ms per token,    11.78 tokens per second)
llama_print_timings:       total time =   15494.16 ms /  1257 tokens

The protocol for managing sepsis in a critical care unit includes aggressive fluid resuscitation, antibiotics, surgical excision of infected or necrotic tissues, drainage of pus, supportive care, and sometimes intensive control of blood glucose and administration of corticosteroids and activated protein C. (Source: Merck Manual, Critical Care Medicine, Chapter 227)

Please note that this response is based on the provided context and may not be applicable to all situations or patients. It is important to consult with a qualified healthcare professional for personalized medical advice and treatment recommendations.

### Question 2: What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?

In [ ]:
question_2 = "What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?"

response_with_rag_2 = generate_rag_response(
    user_input=question_2,
    retriever=retriever,
    llm=lcpp_llm,
    system_message=medical_system_message,
    user_message_template=medical_user_message_template,
    k=5,
    max_tokens=500,
    temperature=0.3,
    top_p=0.95
)

print("Question:", question_2)
print("Answer:", response_with_rag_2)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =     153.85 ms /   250 runs   (    0.62 ms per token,  1625.00 tokens per second)
llama_print_timings: prompt eval time =    2022.63 ms /   827 tokens (    2.45 ms per token,   408.87 tokens per second)
llama_print_timings:        eval time =   19966.79 ms /   249 runs   (   80.19 ms per token,    12.47 tokens per second)
llama_print_timings:       total time =   23208.03 ms /  1076 tokens

Question: What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?
Answer: The common symptoms of appendicitis include epigastric or periumbilical pain followed by brief nausea, vomiting, and anorexia; after a few hours, the pain shifts to the right lower quadrant. Pain increases with cough and motion. Classic signs are right lower quadrant direct and rebound tenderness located at McBurney's point (junction of the middle and outer thirds of the line joining the umbilicus to the anterior superior spine).

Unfortunately, appendicitis cannot be cured via medicine. If left untreated, necrosis, gangrene, and perforation of the appendix can occur, leading to potentially life-threatening complications. The surgical procedure for treating appendicitis is usually an appendectomy, which involves removing the inflamed appendix. The procedure may be laparoscopic or open, depending on the severity of the condition and the patient's overall health.

Source:
"Appendicitis" in The Merck Manual (2022 edition), pp. 342-345.

### Question 3: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?

In [ ]:
question_3 = "What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?"

response_with_rag_3 = generate_rag_response(
    user_input=question_3,
    retriever=retriever,
    llm=lcpp_llm,
    system_message=medical_system_message,
    user_message_template=medical_user_message_template,
    k=5,
    max_tokens=500,
    temperature=0.3,
    top_p=0.95
)

print("Question:", question_3)
print("Answer:", response_with_rag_3)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =      85.94 ms /   148 runs   (    0.58 ms per token,  1722.07 tokens per second)
llama_print_timings: prompt eval time =    2031.83 ms /   877 tokens (    2.32 ms per token,   431.63 tokens per second)
llama_print_timings:        eval time =   11295.72 ms /   147 runs   (   76.84 ms per token,    13.01 tokens per second)
llama_print_timings:       total time =   13961.35 ms /  1024 tokens

Question: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?
Answer: Sudden patchy hair loss can be caused by various factors, including fungal infections, autoimmune disorders, and physical traction. Treatment options depend on the underlying cause. For fungal infections, topical antifungals may be effective. For autoimmune disorders, medications such as corticosteroids or immunosuppressants may be prescribed. In cases of physical traction, eliminating the traction or stress on the scalp can help. It is essential to consult a dermatologist for proper diagnosis and treatment.

Source:
"Alopecia" from the Merck Manuals (2022 edition).

### Question 4:  What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?

In [ ]:
question_4 = "What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?"

response_with_rag_4 = generate_rag_response(
    user_input=question_4,
    retriever=retriever,
    llm=lcpp_llm,
    system_message=medical_system_message,
    user_message_template=medical_user_message_template,
    k=5,
    max_tokens=500,
    temperature=0.3,
    top_p=0.95
)

print("Question:", question_4)
print("Answer:", response_with_rag_4)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =     141.54 ms /   225 runs   (    0.63 ms per token,  1589.62 tokens per second)
llama_print_timings: prompt eval time =    1866.69 ms /   699 tokens (    2.67 ms per token,   374.46 tokens per second)
llama_print_timings:        eval time =   18357.66 ms /   224 runs   (   81.95 ms per token,    12.20 tokens per second)
llama_print_timings:       total time =   21388.63 ms /   923 tokens

Question: What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?
Answer: Treatment for a person with a physical injury to brain tissue depends on the severity and location of the injury, as well as the resulting impairment of brain function. Early intervention by rehabilitation specialists is crucial for maximizing functional recovery. Treatment may include physical and occupational therapy to improve function and prevent secondary disabilities, as well as cognitive therapy for patients with severe cognitive dysfunction. Supportive care should also be provided to prevent systemic complications, provide good nutrition, prevent pressure ulcers, and prevent limb contractures. The specific treatment plan will depend on the patient's abnormalities and the extent of the injury.

Source:
The Merck Manual of Diagnosis & Therapy, 19th Edition, Chapter 172. Function & Dysfunction of the Cerebral Lobes, p. 1811, and Chapter 174. Coma & Impaired Consciousness, p. 1834.

In [ ]:
# Create the DataFrame
import pandas as pd

RAG_result_df = pd.DataFrame({
    "questions": [
        question_1,
        question_2,
        question_3,
        question_4
    ],
    "RAG_responses": [
        response_with_rag_1,
        response_with_rag_2,
        response_with_rag_3,
        response_with_rag_4
    ]
})

# Display the DataFrame
RAG_result_df.head()

,questions,RAG_responses
0,What is the protocol for managing sepsis in a ...,The protocol for managing sepsis in a critical...
1,"What are the common symptoms for appendicitis,...",The common symptoms of appendicitis include ep...
2,What are the effective treatments or solutions...,Sudden patchy hair loss can be caused by vario...
3,What treatments are recommended for a person w...,Treatment for a person with a physical injury ...

## Output Evaluation

In [ ]:
medical_groundedness_rater_system_message = """
You are tasked with rating AI-generated answers to medical questions posed by healthcare professionals.
You will be presented with:
- a medical question (begins with ###Question),
- the context used by the AI (excerpts from Merck Manuals or other authoritative sources, begins with ###Context),
- and the AI-generated answer (begins with ###Answer).

Evaluation criteria:
The task is to judge how well the AI answer is grounded in the provided medical context.

1 - The answer is not grounded in the context at all
2 - The answer is grounded only to a limited extent
3 - The answer is grounded to a good extent
4 - The answer is mostly grounded
5 - The answer is completely grounded in the context

Instructions:
1. List the steps needed to evaluate if the answer strictly uses only the context provided.
2. Provide a step-by-step explanation, comparing the answer with the context and the question.
3. Assign a groundedness score based on the above evaluation.
4. Return only the final score in dictionary format (not JSON), e.g.: {groundedness_score:4}
Score should be in the range 1 to 5.
"""

In [ ]:
medical_relevance_rater_system_message = """
You are tasked with rating AI-generated answers to medical questions posed by healthcare professionals.
You will be presented with:
- a medical question (begins with ###Question),
- the context used by the AI (begins with ###Context),
- and the AI-generated answer (begins with ###Answer).

Evaluation criteria:
The task is to judge how well the answer addresses all important aspects of the medical question, based on the context.

1 - The answer is not relevant at all
2 - The answer is relevant only to a limited extent
3 - The answer is relevant to a good extent
4 - The answer is mostly relevant
5 - The answer is completely relevant

Instructions:
1. List the steps needed to check if the answer fully addresses the key aspects of the question using the context.
2. Provide a step-by-step explanation evaluating the relevance.
3. Assign a relevance score based on the evaluation.
4. Return only the final score in dictionary format (not JSON), e.g.: {relevance_score:4}
Score should be in the range 1 to 5.
"""

In [ ]:
medical_rater_user_message_template = """
###Question
{question}

###Context
{context}

###Answer
{answer}
"""

In [ ]:
def generate_ground_relevance_response(user_input, response, retriever, client,
                                       groundedness_system_message,
                                       relevance_system_message,
                                       user_message_template,
                                       k=5, max_tokens=500, temperature=0, top_p=0.95):

    # Retrieve context and combine into a string
    retrieved_docs = retriever.invoke(user_input)
    retrieved_docs = retrieved_docs[:k]
    context = "\n\n".join([doc.page_content for doc in retrieved_docs])

    # Fill user message template
    user_message = user_message_template.format(
        question=user_input,
        context=context,
        answer=response
    )

    # Groundedness evaluation
    grounded_prompt = groundedness_system_message + "\n\n" + user_message

    grounded_response = client(
        grounded_prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        echo=False
    )

    grounded_result = grounded_response["choices"][0]["text"].strip()

    # Relevance evaluation
    relevance_prompt = relevance_system_message + "\n\n" + user_message

    relevance_response = client(
        relevance_prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        echo=False
    )

    relevance_result = relevance_response["choices"][0]["text"].strip()

    # Return the textual responses
    return grounded_result, relevance_result

#### **Evaluation 1: Prompt Engineering Response Evaluation**

In [ ]:
llm_judge_prompt_ground_1, llm_judge_prompt_rel_1 = generate_ground_relevance_response(
    user_input=question_1,
    response=response_with_rag_1,
    retriever=retriever,
    client=lcpp_llm,
    groundedness_system_message=medical_groundedness_rater_system_message,
    relevance_system_message=medical_relevance_rater_system_message,
    user_message_template=medical_rater_user_message_template
)

# Print the results
print(llm_judge_prompt_ground_1, end="\n\n")
print(llm_judge_prompt_rel_1)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =      26.45 ms /    16 runs   (    1.65 ms per token,   604.98 tokens per second)
llama_print_timings: prompt eval time =    2787.15 ms /  1225 tokens (    2.28 ms per token,   439.52 tokens per second)
llama_print_timings:        eval time =    1018.08 ms /    15 runs   (   67.87 ms per token,    14.73 tokens per second)
llama_print_timings:       total time =    4010.49 ms /  1240 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =     272.13 ms /   500 runs   (    0.54 ms per token,  1837.38 tokens per second)
llama_print_timings: prompt eval time =    2655.61 ms /  1151 tokens (    2.31 ms per token,   433.42 tokens per second)
llama_print_timings:        eval time =   39364.70 ms /   499 runs   (   78.89 ms per token,    12.68 tokens per second)
llama_print_timings:       total time =   44553.27 ms /  1650 tokens

Please evaluate the answer based on the provided context and instructions.

In [ ]:
llm_judge_prompt_ground_2, llm_judge_prompt_rel_2 = generate_ground_relevance_response(
    user_input=question_2,
    response=response_with_rag_2,
    retriever=retriever,
    client=lcpp_llm,
    groundedness_system_message=medical_groundedness_rater_system_message,
    relevance_system_message=medical_relevance_rater_system_message,
    user_message_template=medical_rater_user_message_template
)

print(llm_judge_prompt_ground_2, end="\n\n")
print(llm_judge_prompt_rel_2)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =       8.95 ms /    16 runs   (    0.56 ms per token,  1788.51 tokens per second)
llama_print_timings: prompt eval time =    3010.15 ms /  1314 tokens (    2.29 ms per token,   436.52 tokens per second)
llama_print_timings:        eval time =    1115.12 ms /    15 runs   (   74.34 ms per token,    13.45 tokens per second)
llama_print_timings:       total time =    4198.72 ms /  1329 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =     274.93 ms /   500 runs   (    0.55 ms per token,  1818.68 tokens per second)
llama_print_timings: prompt eval time =    3023.38 ms /  1291 tokens (    2.34 ms per token,   427.01 tokens per second)
llama_print_timings:        eval time =   39521.92 ms /   499 runs   (   79.20 ms per token,    12.63 tokens per second)
llama_print_timings:       total time =   45091.35 ms /  1790 tokens

Please evaluate the answer based on the provided context and question.

In [ ]:
llm_judge_prompt_ground_3, llm_judge_prompt_rel_3 = generate_ground_relevance_response(
    user_input=question_3,
    response=response_with_rag_3,
    retriever=retriever,
    client=lcpp_llm,
    groundedness_system_message=medical_groundedness_rater_system_message,
    relevance_system_message=medical_relevance_rater_system_message,
    user_message_template=medical_rater_user_message_template
)

print(llm_judge_prompt_ground_3, end="\n\n")
print(llm_judge_prompt_rel_3)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =      20.81 ms /    22 runs   (    0.95 ms per token,  1057.39 tokens per second)
llama_print_timings: prompt eval time =    2860.76 ms /  1262 tokens (    2.27 ms per token,   441.14 tokens per second)
llama_print_timings:        eval time =    1500.06 ms /    21 runs   (   71.43 ms per token,    14.00 tokens per second)
llama_print_timings:       total time =    4512.42 ms /  1283 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =      14.93 ms /    18 runs   (    0.83 ms per token,  1205.38 tokens per second)
llama_print_timings: prompt eval time =    2874.08 ms /  1239 tokens (    2.32 ms per token,   431.10 tokens per second)
llama_print_timings:        eval time =    1270.44 ms /    17 runs   (   74.73 ms per token,    13.38 tokens per second)
llama_print_timings:       total time =    4263.01 ms /  1256 tokens

Please evaluate the answer based on the provided criteria and provide the final groundedness score.

Please evaluate the relevance of the answer based on the given context.

In [ ]:
llm_judge_prompt_ground_4, llm_judge_prompt_rel_4 = generate_ground_relevance_response(
    user_input=question_4,
    response=response_with_rag_4,
    retriever=retriever,
    client=lcpp_llm,
    groundedness_system_message=medical_groundedness_rater_system_message,
    relevance_system_message=medical_relevance_rater_system_message,
    user_message_template=medical_rater_user_message_template
)

print(llm_judge_prompt_ground_4, end="\n\n")
print(llm_judge_prompt_rel_4)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =      10.60 ms /    19 runs   (    0.56 ms per token,  1792.96 tokens per second)
llama_print_timings: prompt eval time =    2803.11 ms /  1161 tokens (    2.41 ms per token,   414.18 tokens per second)
llama_print_timings:        eval time =    1317.70 ms /    18 runs   (   73.21 ms per token,    13.66 tokens per second)
llama_print_timings:       total time =    4207.58 ms /  1179 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =      10.09 ms /    16 runs   (    0.63 ms per token,  1586.04 tokens per second)
llama_print_timings: prompt eval time =    2713.97 ms /  1138 tokens (    2.38 ms per token,   419.31 tokens per second)
llama_print_timings:        eval time =    1108.89 ms /    15 runs   (   73.93 ms per token,    13.53 tokens per second)
llama_print_timings:       total time =    3933.27 ms /  1153 tokens

Please evaluate the answer and provide a groundedness score based on the provided criteria.

Please evaluate the relevance of the answer based on the context provided.

In [ ]:
# Create a DataFrame to store the evaluation results
prompt_evaluation_df = pd.DataFrame({
    "question": [
        question_1,
        question_2,
        question_3,
        question_4
    ],
    "base_prompt_response": [
        response_with_rag_1,
        response_with_rag_2,
        response_with_rag_3,
        response_with_rag_4
    ],
    "groundedness_score": [
        llm_judge_prompt_ground_1,
        llm_judge_prompt_ground_2,
        llm_judge_prompt_ground_3,
        llm_judge_prompt_ground_4
    ],
    "relevance_score": [
        llm_judge_prompt_rel_1,
        llm_judge_prompt_rel_2,
        llm_judge_prompt_rel_3,
        llm_judge_prompt_rel_4
    ]
})

prompt_evaluation_df["groundedness_score"] = pd.to_numeric(
    prompt_evaluation_df["groundedness_score"], errors="coerce"
)

prompt_evaluation_df["relevance_score"] = pd.to_numeric(
    prompt_evaluation_df["relevance_score"], errors="coerce"
)

display(prompt_evaluation_df)

,question,base_prompt_response,groundedness_score,relevance_score
0,What is the protocol for managing sepsis in a ...,The protocol for managing sepsis in a critical...,NaN,NaN
1,"What are the common symptoms for appendicitis,...",The common symptoms of appendicitis include ep...,NaN,NaN
2,What are the effective treatments or solutions...,Sudden patchy hair loss can be caused by vario...,NaN,NaN
3,What treatments are recommended for a person w...,Treatment for a person with a physical injury ...,NaN,NaN

#### **Observations:**
* The evaluation framework was successfully applied to assess the generated responses based on groundedness and relevance using predefined medical evaluation criteria.

* Although the responses were evaluated, the groundedness and relevance scores were not displayed because the returned outputs were not converted into numeric values before storing them in the DataFrame.

#### **Evaluation 2: RAG Response Evaluation**

In [ ]:
RAG_ground_1, RAG_rel_1 = generate_ground_relevance_response(
    user_input=question_1,
    response=response_with_rag_1,
    retriever=retriever,
    client=lcpp_llm,
    groundedness_system_message=medical_groundedness_rater_system_message,
    relevance_system_message=medical_relevance_rater_system_message,
    user_message_template=medical_rater_user_message_template
)

# Print the results
print(RAG_ground_1, end="\n\n")
print(RAG_rel_1)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =      10.94 ms /    16 runs   (    0.68 ms per token,  1462.92 tokens per second)
llama_print_timings: prompt eval time =    3025.03 ms /  1174 tokens (    2.58 ms per token,   388.10 tokens per second)
llama_print_timings:        eval time =    1174.60 ms /    15 runs   (   78.31 ms per token,    12.77 tokens per second)
llama_print_timings:       total time =    4295.68 ms /  1189 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =     275.14 ms /   500 runs   (    0.55 ms per token,  1817.26 tokens per second)
llama_print_timings: prompt eval time =    2980.34 ms /  1151 tokens (    2.59 ms per token,   386.20 tokens per second)
llama_print_timings:        eval time =   39635.70 ms /   499 runs   (   79.43 ms per token,    12.59 tokens per second)
llama_print_timings:       total time =   45170.20 ms /  1650 tokens

Please evaluate the answer based on the provided context and instructions.

In [ ]:
RAG_ground_2, RAG_rel_2 = generate_ground_relevance_response(
    user_input=question_2,
    response=response_with_rag_2,
    retriever=retriever,
    client=lcpp_llm,
    groundedness_system_message=medical_groundedness_rater_system_message,
    relevance_system_message=medical_relevance_rater_system_message,
    user_message_template=medical_rater_user_message_template
)

# Print the results
print(RAG_ground_2, end="\n\n")
print(RAG_rel_2)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =      11.32 ms /    16 runs   (    0.71 ms per token,  1412.93 tokens per second)
llama_print_timings: prompt eval time =    2987.88 ms /  1314 tokens (    2.27 ms per token,   439.78 tokens per second)
llama_print_timings:        eval time =    1043.89 ms /    15 runs   (   69.59 ms per token,    14.37 tokens per second)
llama_print_timings:       total time =    4145.83 ms /  1329 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =     274.47 ms /   500 runs   (    0.55 ms per token,  1821.72 tokens per second)
llama_print_timings: prompt eval time =    2971.64 ms /  1291 tokens (    2.30 ms per token,   434.44 tokens per second)
llama_print_timings:        eval time =   40342.89 ms /   499 runs   (   80.85 ms per token,    12.37 tokens per second)
llama_print_timings:       total time =   45880.39 ms /  1790 tokens

Please evaluate the answer based on the provided context and question.

In [ ]:
RAG_ground_3, RAG_rel_3 = generate_ground_relevance_response(
    user_input=question_3,
    response=response_with_rag_3,
    retriever=retriever,
    client=lcpp_llm,
    groundedness_system_message=medical_groundedness_rater_system_message,
    relevance_system_message=medical_relevance_rater_system_message,
    user_message_template=medical_rater_user_message_template
)

# Print the results
print(RAG_ground_3, end="\n\n")
print(RAG_rel_3)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =      84.06 ms /    22 runs   (    3.82 ms per token,   261.72 tokens per second)
llama_print_timings: prompt eval time =    2804.99 ms /  1262 tokens (    2.22 ms per token,   449.91 tokens per second)
llama_print_timings:        eval time =    1403.51 ms /    21 runs   (   66.83 ms per token,    14.96 tokens per second)
llama_print_timings:       total time =    4754.86 ms /  1283 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =       8.98 ms /    18 runs   (    0.50 ms per token,  2004.01 tokens per second)
llama_print_timings: prompt eval time =    2841.68 ms /  1239 tokens (    2.29 ms per token,   436.01 tokens per second)
llama_print_timings:        eval time =    1293.52 ms /    17 runs   (   76.09 ms per token,    13.14 tokens per second)
llama_print_timings:       total time =    4214.91 ms /  1256 tokens

Please evaluate the answer based on the provided criteria and provide the final groundedness score.

Please evaluate the relevance of the answer based on the given context.

In [ ]:
RAG_ground_4, RAG_rel_4 = generate_ground_relevance_response(
    user_input=question_4,
    response=response_with_rag_4,
    retriever=retriever,
    client=lcpp_llm,
    groundedness_system_message=medical_groundedness_rater_system_message,
    relevance_system_message=medical_relevance_rater_system_message,
    user_message_template=medical_rater_user_message_template
)

# Print the results
print(RAG_ground_4, end="\n\n")
print(RAG_rel_4)

Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =      10.32 ms /    19 runs   (    0.54 ms per token,  1841.26 tokens per second)
llama_print_timings: prompt eval time =    2872.40 ms /  1161 tokens (    2.47 ms per token,   404.19 tokens per second)
llama_print_timings:        eval time =    1389.25 ms /    18 runs   (   77.18 ms per token,    12.96 tokens per second)
llama_print_timings:       total time =    4345.44 ms /  1179 tokens
Llama.generate: prefix-match hit

llama_print_timings:        load time =     437.12 ms
llama_print_timings:      sample time =       7.90 ms /    16 runs   (    0.49 ms per token,  2024.80 tokens per second)
llama_print_timings: prompt eval time =    2833.33 ms /  1138 tokens (    2.49 ms per token,   401.65 tokens per second)
llama_print_timings:        eval time =    1150.19 ms /    15 runs   (   76.68 ms per token,    13.04 tokens per second)
llama_print_timings:       total time =    4053.34 ms /  1153 tokens

Please evaluate the answer and provide a groundedness score based on the provided criteria.

Please evaluate the relevance of the answer based on the context provided.

In [ ]:
# Create a DataFrame to store the RAG evaluation results
RAG_evaluation_df = pd.DataFrame({
    "question": [
        question_1,
        question_2,
        question_3,
        question_4
    ],
    "RAG_response": [
        response_with_rag_1,
        response_with_rag_2,
        response_with_rag_3,
        response_with_rag_4
    ],
    "groundedness_score": [
        RAG_ground_1,
        RAG_ground_2,
        RAG_ground_3,
        RAG_ground_4
    ],
    "relevance_score": [
        RAG_rel_1,
        RAG_rel_2,
        RAG_rel_3,
        RAG_rel_4
    ]
})

# Convert scores to numeric
RAG_evaluation_df["groundedness_score"] = pd.to_numeric(
    RAG_evaluation_df["groundedness_score"],
    errors="coerce"
)

RAG_evaluation_df["relevance_score"] = pd.to_numeric(
    RAG_evaluation_df["relevance_score"],
    errors="coerce"
)

# Display the DataFrame
display(RAG_evaluation_df)

,question,RAG_response,groundedness_score,relevance_score
0,What is the protocol for managing sepsis in a ...,The protocol for managing sepsis in a critical...,NaN,NaN
1,"What are the common symptoms for appendicitis,...",The common symptoms of appendicitis include ep...,NaN,NaN
2,What are the effective treatments or solutions...,Sudden patchy hair loss can be caused by vario...,NaN,NaN
3,What treatments are recommended for a person w...,Treatment for a person with a physical injury ...,NaN,NaN

#### **Observations:**
* The RAG evaluation was completed to assess the responses generated using the retrieved medical context, enabling comparison with the prompt engineering approach.
* The evaluation scores appear as NaN because the groundedness and relevance
outputs were not successfully extracted and converted into numeric values before storing them in the DataFrame.

## Actionable Insights and Business Recommendations

#### **Actionable insights**

* Integrating Retrieval-Augmented Generation (RAG) with trusted medical documents can improve the reliability and context-awareness of AI-generated healthcare responses.

* Implementing automated evaluation metrics such as groundedness and relevance helps monitor response quality and identify areas for improvement.

#### **Recommendations**

* Improve the evaluation pipeline by correctly extracting and storing groundedness and relevance scores instead of displaying NaN values.

* Enhance the RAG system by optimizing document chunking, retrieval parameters, and embedding quality to provide more accurate and context-specific medical answers.

<font size=6 color='#4682B4'>Power Ahead</font>
___